### ISSUE TITLE
Displaying large dates

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/paleoPandas#11]
Pandas' datetime formatting options make a lot of sense for contemporary dates (ISO8601 format) like 2023-01-18 21:23:06.  This makes little sense in a paleo context, so we need a way to display dates in the dataframes that takes advantage of units/context.

Currently,  [Pyleoclim](https://github.com/LinkedEarth/Pyleoclim_util/tree/new-objects) bypasses this issue by assigning the `time` variable as a new axis to the `pd.Series` object for display purposes. Is this the best strategy? It also seems like we could be leveraging the NumPy `view()` functionality with something like `.view("M8[100Y]")`.  Think big: if I have a series of 2 Ga every with a data point every 50 million years, how would we display this?

**Comment by MarcoGorelli** [comment]
I'd suggest just displaying `self.time` and `self.time_unit`, pandas' repr of datetimeindex is unlikely to change anytime soon

**Comment by CommonClimate** [comment]
Yes, that's what is currently being done in `__repr__` and `.view()`. Closing this as we've got better things to do.
