### ISSUE TITLE
resample() method

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/paleoPandas#12]
Resampling is  likely to be one of the most useful capabilities afforded by pandas to Pyleoclim or other paleo-oriented packages.

Because the pandas (NumPy) time semantics currently max out at "Y", resampling a million-year series at 5ka intervals would be tedious. Try 2 Ga at 5 Ma intervals! 

Proposal: 
- generalize the pandas time semantics; OR
- create an API-level function in Pyleoclim ('new-objects' branch)  that uses pd.resample() under the hood, but allows workable UX and semantics for paleo users (e.g. `ts.resample('5ka')` for resampling on 5000y intervals).

**Comment by kcpevey** [comment]
Currently blocked by #26

**Comment by kcpevey** [comment]
Complete within pyleoclim_util, still waiting on upstream changes in pandas for full functionality.
