### ISSUE TITLE
MultipleSeries to dataframe

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/paleoPandas#13]
Generalizing the creation of Series objects from a dataFrame would be very helpful. See  Dry_Tortugas.ipynb for an example: currently we create different Series manually (one per dataframe column), but it would be very helpful to have a `pyleo.MultipleSeries` methods called `from_pandas()` that would take the following arguments:

- df, a Pandas dataframe
- time_col, name or index of the time used to create the time variable, hence the datetime index
- value_cols: index of the columns to be exported into a MultipleSeries object (typically, users will only want certain columns from a spreadsheet)

metadata can be inferred from the spreadsheet columns (e.g. a string in parentheses is likely to be the `value_unit` of the corresponding Series, like "mmol/mol" in this example; the string preceding that parenthesis ("Sr/Ca" in this example) will be the `value_name` of the corresponding Series, or the `name` of the pd.Series created from that column of the DataFrame.    Similarly, metadata for the time variable (particularly the all-important `time_unit`) can be inferred from the header of `df.iloc[:,time_col]`. 

The method should return a MultipleSeries object (i.e. a list of `pyleo.Series` objects).

**Comment by CommonClimate** [comment]
I take Deborah's point that this will be impossible to do for general cases, because each paleo spreadsheet is a bit of a snowflake.  However, the reverse is possible: `pyleo.MultipleSeries` objects should have a `to_pandas()` method just like `pyleo.Series` objects do. Instead of exporting to `pd.Series`, it would export to `pd.DataFrame`. This would likely require some kind of alignment to make place, therefore issue #28 takes precedence.

**Comment by MarcoGorelli** [comment]
So `MultipleSeries.from_pandas` is no longer a requirement?

`MultipleSeries.to_pandas` - doesn't look like this requires #28 to be done first, given that you already have a way of aligning Series

**Comment by CommonClimate** [comment]
Addressed by https://github.com/LinkedEarth/Pyleoclim_util/pull/335

**Comment by CommonClimate** [comment]
Question re: this. As shown in Paleopandas Playground.ipynb, I get a result like this in my test case:
<img width="638" alt="Screen Shot 2023-02-23 at 16 46 42" src="https://user-images.githubusercontent.com/13760223/221064447-94e2b708-0ca8-420d-a7cd-d454ac5a430f.png">

this is too good to be true: all three Series in this object have completely different time axes, so I don't understand how the df appears to have one common index to them all and no missing values (NaNs). Looking into the function, I see that it applies `common_time()` under the hood, but I think this should be an optional parameter. The default behavior should be to align the timeseries to the same index, but keep NaNs in the DataFrame, unless you see a major objection to that. At the very least, users need to be warned that common_time() has been applied, and what method was used.  I can actually do that my applying the concept of log (present in Series) to this class as well.

**Comment by CommonClimate** [comment]
addressed by [#350](https://github.com/LinkedEarth/Pyleoclim_util/pull/350)
