### ISSUE TITLE
Add simple way to remove Series from MultiSeries

### ISSUE THREAD

**Issue by kcpevey** [LinkedEarth/paleoPandas#17]
Since MultiSeries is effectively a list, we need a small function which will handle removing a single series. 

Perhaps something like this:  
`MultiSeries.remove(labels=[“SOI_data”])`  

This would remove the single series with the label `SOI_data` from the MultiSeries.

**Comment by CommonClimate** [comment]
Yes, and it would be nice to be able to use an overloaded method like `ms - labels`, where ms is a `MultipleSeries` object and labels is a list of the Series labels.

**Comment by MarcoGorelli** [comment]
What's the advantage of using an overloaded method?

`ms.remove(labels)` looks a lot clearer to me than `ms - labels`

If someone reads `ms.remove(labels)`, and they don't know what it does, then they know where to look in the docs: `MultipleSeries.remove`.
If someone sees `ms - labels`, and they don't know what that does, then how do they know where to look in the docs?

**Comment by CommonClimate** [comment]
Yes, fair point. An overloaded method might be more useful for creating a MS object quickly, but removal is a more delicate operation, so should have a higher barrier to entry.

**Comment by CommonClimate** [comment]
Addressed by https://github.com/LinkedEarth/Pyleoclim_util/pull/337
