### ISSUE TITLE
Add single Series to MultiSeries object

### ISSUE THREAD

**Issue by kcpevey** [LinkedEarth/paleoPandas#18]
We need a way to add a single Series to a MultiSeries object. 

Perhaps something like this:  
`MultiSeries.add(Series)`  
or  
`MultiSeries.add([Series1, Series2])`

**Comment by CommonClimate** [comment]
That's an incremental improvement over our current process, which we can easily do ourselves.  We'd be more interested in an overloaded method, so that `ms + ts1 + ts2` would append the Series objects `ts1` and `ts2` to an existing MultipleSeries object `ms`

**Comment by CommonClimate** [comment]
I've tested this and it works well
