### ISSUE TITLE
Combine two MultiSeries objects

### ISSUE THREAD

**Issue by kcpevey** [LinkedEarth/paleoPandas#19]
We need a way to combine two MultiSeries objects. I'm opening this as a separate action item, but I actually think it can be handled in the same way as #18 - via a `MultiSeries.add` method. 

`MultiSeries.add(MultiSeries)` could detect accept different types (Series, MultiSeries, list of Series) and handle them appropriately.

**Comment by CommonClimate** [comment]
yes, and same as #18: overloaded + or & method would be most valuable as a shorthand.

**Comment by CommonClimate** [comment]
the new `Series.equals()` method should help

**Comment by MarcoGorelli** [comment]
from our side, is this one covered by https://github.com/LinkedEarth/paleoPandas/issues/18, or is there anything else which needs doing here?

**Comment by CommonClimate** [comment]
it is not covered.  See the latest version of Paleopandas Playground.ipynb for an illustration. AFAICT, #18 only allows to a a Series to a MultipleSeries object, not to combine two MultipleSeries objects. This still needs to be done by the end of the project, but I'm guessing won't be huge ordeal?

**Comment by CommonClimate** [comment]
Addressed by #354 . Still needs a notebook tutorial, or at least informative docstrings on __and__ and __add__ to highlight usage differences.
