### ISSUE TITLE
Test equality of two Series or MultipleSeries objects

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/paleoPandas#20]
In discussing how to add or remove Series objects from a MultipleSeries object, I realize we need a way to test whether Series are the same, particularly:
- to check that some reversible transformation was performed correctly
- in case someone tries to add a Series to a MultipleSeries object that already contains it
- in case someone wants to remove a Series from a MultipleSeries object

Proposal: create a new method `Series.equals()` inspired by `pandas.Series.equals()`, and testing for equality of the data themselves (using `Series.from_pandas()`) and  the metadata. Offer various caveats in case the data are equal, but not the metadata.

**Comment by CommonClimate** [comment]
@MarcoGorelli just one question: should this be a class method?

**Comment by CommonClimate** [comment]
prototype in [new objects branch](https://github.com/LinkedEarth/Pyleoclim_util/commit/b4dacb5c29bded190377a534e5bad0d29b6a6b3d)

**Comment by MarcoGorelli** [comment]
Hi @CommonClimate - why do you need this? Wasn't the suggestion to remove Series from `MultipleSeries` by label?

**Comment by MarcoGorelli** [comment]
> @MarcoGorelli just one question: should this be a class method?

wouldn't need to be, no

> prototype in [new objects branch](https://github.com/LinkedEarth/Pyleoclim_util/commit/b4dacb5c29bded190377a534e5bad0d29b6a6b3d)

is this the right link? I had a look, and it that commit does something else entirely (`new view() shorthand. time_unit now mandatory `)

**Comment by CommonClimate** [comment]
The method is useful to make sure they aren't duplicates in the MS object. One can also imagine a slight variant that identifies a Series with the same data, but different metadata. In any case, it's fine if you don't need it, I just thought it could come in handy at some point and was quite easy to make.

**Comment by MarcoGorelli** [comment]
Sure, I can see how it's useful when adding to a MultipleSeries - you need to validate that there aren't duplicates. Looks fine.

It's

> in case someone wants to remove a Series from a MultipleSeries object

that I think we need alignment on. Are we doing

```
def remove(self, labels: list[str])
```
or
```
def remove(self, series: list[pyleoclim.Series])
```
?
If it's the former (which is what I'd understood), then we just remove the `Series` corresponding to the given labels, and there's no equality to check?

Anyway, the way you've implemented it looks fine to me (you might want to show the diff if the metadata are different to make it easier for users to see why they're different, just a suggestion)

**Comment by CommonClimate** [comment]
Hi @MarcoGorelli .
Agreed, we should be doing `def remove(self, labels: list[str])`. My original comment was motivated by doing something like `ms - ts` as discussed earlier, but that is no longer relevant.   Where the equality check does come in, is in identifying the labels to remove. Suppose I have a MS object with 100 series, and I want to remove a particular series from that list. It can scroll through endless plots or try to hunt for a label in the list, but I want to be sure that I'm removing the right one. In that case, it could be useful to have a method called `ms.find_series()` that checks for equality and returns the index and label of the Series in question so it can be targeted by `ms.remove(label)` (possibly, the Series might be hiding under a different label, or with slightly different metadata, but contain the same actual data).  That's something I can build in the future, so no reason for you to worry about it.

> Anyway, the way you've implemented it looks fine to me (you might want to show the diff if the metadata are different to make it easier for users to see why they're different, just a suggestion)

Good idea. What do you suggest I use for displaying that?

**Comment by CommonClimate** [comment]
dropping this to low priority

**Comment by MarcoGorelli** [comment]
> Good idea. What do you suggest I use for displaying that?

How about something like
```
        same_metadata = (self.metadata == ts.metadata)
        if not same_metadata:
            for key in self.metadata:
                if self.metadata.get(key) != ts.metadata.get(key):
                    print("metadata differs at key {key}, left: {self.metadata.get(key)}, right: {ts.metadata.get(key)}")
            print("Difference found among the 2 Series'' metadata")
```

**Comment by CommonClimate** [comment]
Great suggestion. I incorporated that into the new-objects branch, see 8efb31c

**Comment by CommonClimate** [comment]
I think we can close this when this is resolved: https://github.com/LinkedEarth/Pyleoclim_util/issues/316
