### ISSUE TITLE
load_dataset() method

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/paleoPandas#21]
I’d like to have Pyleoclim ship with a few key datasets that we can easily load for testing and docs, the way it’s done in [Seaborn](https://seaborn.pydata.org/tutorial/introduction.html):

`tips = sns.load_dataset("tips")`

The datasets would be a subset of what is currently in the `data` directory of this repository.

**Comment by CommonClimate** [comment]
Considerations: 
- which datasets to include? SOI, LR04, and ... ?
- save in original format (csv, lipd) or as JSON objects?

**Comment by kcpevey** [comment]
>save in original format (csv, lipd) or as JSON objects?

Since the files are being stored in git, ASCII files are preferred. This is because a sensible git-diff can be done. So a minor change to a csv or JSON file will cause minimal changes in the "eyes" of git, but a minor change to a binary file will always have the effect of completely rewriting the file. It just adds bulk to the git history.

That said, you probably need to test against each of the file types that the package can read from.

One way that I've done this in the past is to add a data folder in the package and put something like this in the package `__init__.py`:
```
PACKAGE_DIR = Path(__file__).parent.resolve()
DATA_DIR = PACKAGE_DIR.joinpath("data").resolve()
```

It looks like you already have `include_package_data=True,` in your `setup.py` so those files will be included by default. There are other alternatives as well. You can add the `data` folder outside of the package, then in `setup.py` you'd need to add a `data_files` or `package_data` to point to them.

You'll also need to add a helper function to link between dataset name and the path to the data. I assume you'll also be loading the data inside this function. 

Given that you have a few 10s of KB sample files, I think the above approach is the easiest to build and maintain. You mentioned how seaborn does something similar. They actually keep their sample data in a separate repo and also implement some smart cacheing. Their `load_dataset` function is [here](https://github.com/seaborn/seaborn/blob/d1c04f2c2c4dbd11ede016405b5ea51380e37f51/seaborn/utils.py#L531) if you want to take a look. Your method may look similar.

**Comment by khider** [comment]
Soon the package won't be reading from LiPD directly so I would say let's concentrate on JSON/csv and make it as small as possible

**Comment by CommonClimate** [comment]
Agreed. For docstring examples that use lipd files, we can leverage the lipdverse via `pylipd` when that is operational, but for now let's focus on JSON or CSV datasets.  @khider , I was thinking of having:
- LR04
- SOI
- NINO3-AIR (for Coherency, Correlations, etc)
- HadCRUT5 (for trends)

Anything else?

**Comment by kcpevey** [comment]
@CommonClimate can you confirm the source for those files?

* LR04: https://github.com/LinkedEarth/paleoPandas/blob/main/data/LR04.csv
* SOI: I'm assuming you want this one (https://github.com/LinkedEarth/paleoPandas/blob/main/data/soi_data.csv) since it had an edit 6 days ago?
* NINO3-AIR: unsure, maybe oni.csv?
* HadCRUT5: 'https://www.metoffice.gov.uk/hadobs/hadcrut5/data/current/analysis/diagnostics/HadCRUT.5.0.1.0.analysis.summary_series.global.annual.csv' ?

**Comment by CommonClimate** [comment]
Yes to all the ones you had, and good find on the HadCRUT5 one. 

Re: NINO3-AIR, sorry for being so terse; it is in fact this dataset: https://github.com/LinkedEarth/Pyleoclim_util/blob/master/example_data/wtc_test_data_nino_even.csv
I would all it by the label "NINO3-AIR", though. 
Let me know if you hit any roadblocks!

**Comment by CommonClimate** [comment]
Just having those datasets would save us a huge amount of work, and we can always add more when we see how you've done it.

**Comment by CommonClimate** [comment]
Hi @kcpevey, I was able to load datasets correctly yesterday in an old environment, but I had to build a new one so I can test @MarcoGorelli 's resample() PR.  When I try to load the NINO3 dataset, I get the following error, which seems to imply that Python is not looking for `metadata.yml` in the right place:

```
ts = pyleo.utils.load_dataset('nino3')
Traceback (most recent call last):

  Cell In[3], line 1
    ts = pyleo.utils.load_dataset('nino3')

  File ~/opt/miniconda3/envs/pyleopd/lib/python3.10/site-packages/pyleoclim/utils/datasets.py:71 in load_dataset
    metadata = get_metadata(name)

  File ~/opt/miniconda3/envs/pyleopd/lib/python3.10/site-packages/pyleoclim/utils/datasets.py:51 in get_metadata
    all_metadata = load_datasets_metadata()

  File ~/opt/miniconda3/envs/pyleopd/lib/python3.10/site-packages/pyleoclim/utils/datasets.py:25 in load_datasets_metadata
    with open(path, "r") as stream:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/julieneg/opt/miniconda3/envs/pyleopd/lib/python3.10/site-packages/example_data/metadata.yml'
```

I conda-installed everything from the package's `environment.yml` (commenting out the offending Linux package thing), so I am not sure what is wrong here. How would we troubleshoot?  Here's what's in the environment:


Package                       Version
----------------------------- ---------------------------
anyio                         3.6.2
appdirs                       1.4.4
appnope                       0.1.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     2.2.1
attrs                         22.2.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
bagit                         1.8.1
beautifulsoup4                4.11.1
bleach                        6.0.0
bokeh                         3.0.3
Bottleneck                    1.3.4
brotlipy                      0.7.0
Cartopy                       0.21.0
certifi                       2022.12.7
cffi                          1.15.1
cftime                        1.6.2
charset-normalizer            2.1.1
click                         8.1.3
climlab                       0.7.13
cloudpickle                   2.2.1
colorama                      0.4.6
comm                          0.1.2
contourpy                     1.0.7
cryptography                  39.0.0
cycler                        0.11.0
Cython                        3.0.0a11
cytoolz                       0.12.0
dask                          2022.8.0
debugpy                       1.6.6
decorator                     5.1.1
defusedxml                    0.7.1
demjson3                      3.0.6
dill                          0.3.6
distributed                   2022.8.0
entrypoints                   0.4
exceptiongroup                1.1.0
executing                     1.2.0
fastjsonschema                2.16.2
flit_core                     3.8.0
fonttools                     4.38.0
fsspec                        2023.1.0
future                        0.18.3
HeapDict                      1.0.1
idna                          3.4
importlib-metadata            6.0.0
importlib-resources           5.10.2
iniconfig                     2.0.0
ipykernel                     6.21.0
ipython                       8.9.0
ipython-genutils              0.2.0
ipywidgets                    8.0.4
jedi                          0.18.2
Jinja2                        3.1.2
joblib                        1.2.0
jsonschema                    4.17.3
jupyter                       1.0.0
jupyter-client                7.3.4
jupyter-console               6.4.4
jupyter_core                  5.2.0
jupyter-server                1.23.5
jupyterlab-pygments           0.2.2
jupyterlab-widgets            3.0.5
kiwisolver                    1.4.4
LiPD                          0.2.8.8
llvmlite                      0.39.1
locket                        1.0.0
lz4                           4.2.0
MarkupSafe                    2.1.2
matplotlib                    3.6.3
matplotlib-inline             0.1.6
mistune                       2.0.4
msgpack                       1.0.4
multiprocess                  0.70.14
munkres                       1.1.4
nbclassic                     0.4.8
nbclient                      0.7.2
nbconvert                     7.2.9
nbformat                      5.7.3
nest-asyncio                  1.5.6
netCDF4                       1.5.8
networkx                      3.0
nibabel                       5.0.0
nitime                        0.9
notebook                      6.5.2
notebook_shim                 0.2.2
numba                         0.56.4
numpy                         1.22.0
packaging                     23.0
pandas                        2.0.0.dev0+1354.gcc6c9570aa
pandocfilters                 1.5.0
parso                         0.8.3
partd                         1.3.0
pathos                        0.3.0
patsy                         0.5.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           23.0
pkgutil_resolve_name          1.3.10
platformdirs                  2.6.2
pluggy                        1.0.0
ply                           3.11
pooch                         1.6.0
pox                           0.3.2
ppft                          1.7.6.6
prometheus-client             0.16.0
prompt-toolkit                3.0.36
psutil                        5.9.4
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycparser                     2.21
Pygments                      2.14.0
pyhht                         0.1.0
pyleoclim                     1.0.0b0
pyOpenSSL                     23.0.0
pyparsing                     3.0.9
pyproj                        3.4.1
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
pyrsistent                    0.19.3
pyshp                         2.3.1
PySocks                       1.7.1
pytest                        7.2.1
python-dateutil               2.8.2
pytz                          2022.7.1
PyYAML                        6.0
pyzmq                         25.0.0
qtconsole                     5.4.0
QtPy                          2.3.0
requests                      2.28.2
scikit-learn                  1.3.dev0
scipy                         1.10.0
seaborn                       0.12.2
Send2Trash                    1.8.0
setuptools                    66.1.1
Shapely                       1.8.5.post1
sip                           6.7.6
six                           1.16.0
sniffio                       1.3.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
spyder-kernels                2.4.1
stack-data                    0.6.2
statsmodels                   0.14.0.dev674+g8aa78bea5
tabulate                      0.9.0
tblib                         1.7.0
terminado                     0.17.1
tftb                          0.1.4
threadpoolctl                 3.1.0
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
tornado                       6.1
tqdm                          4.64.1
traitlets                     5.9.0
typing_extensions             4.4.0
unicodedata2                  15.0.0
Unidecode                     1.3.6
urllib3                       1.26.14
wcwidth                       0.2.6
webencodings                  0.5.1
websocket-client              1.5.0
wget                          3.2
wheel                         0.38.4
widgetsnbextension            4.0.5
wurlitzer                     3.0.3
xarray                        2022.6.0
xlrd                          2.0.1
xyzservices                   2022.9.0
zict                          2.2.0
zipp                          3.12.0

**Comment by kcpevey** [comment]
TODO:
* [ ] add example notebook
* [ ] add remaining datasets
* [ ] decide on an approach

**Comment by khider** [comment]
We need to go through our example data folder and make some decisions on what to keep. I would say the 4 that @CommonClimate listed are a good start

**Comment by CommonClimate** [comment]
Yes, and Deborah and I are discussing a good example of a MultipleSeries object, which will be required to test/demo that part of the package.

**Comment by CommonClimate** [comment]
re: "decide on an approach", isn't this resolved now? (metadata.yml)

**Comment by kcpevey** [comment]
Yes, just marked it as resolved per the discussion [here](https://github.com/LinkedEarth/Pyleoclim_util/pull/301)

**Comment by kcpevey** [comment]
Per the meeting today, I'll un-assign myself to this one and let USC take over :)

**Comment by CommonClimate** [comment]
@khider we need easily loadable examples of 
- MultipleSeries
- EnsembleSeries

I see that the Pyleoclim repo's example_data folder currently contains a file called `crystalcave_ens.json`. Should this be added to our list of loadable datasets? If so, can you do that?  For MultipleSeries, do we want to wait for pyLipd to be able to load the Euro2k dataset or can there be a json solution to that?

**Comment by CommonClimate** [comment]
Closing this as the method now exists and works well ; we can always add more datasets later.

**Comment by CommonClimate** [comment]
This is what we have now: 
 'SOI',
    'NINO3',
    'HadCRUT5',
    'AIR',
    'LR04',
    'AACO2',
    'nino_json'

**Comment by CommonClimate** [comment]
Just one question for @kcpevey : how would users know what datasets are available? Is there an easy way for them to pull info from metadata.yml?

**Comment by CommonClimate** [comment]
Sounds perfect, thank you!
Speaking of documentation: we've decided to make ours more minimal, and pandas-like, so the usual >>> syntax works. Please let us know if you have any questions on this!
