### ISSUE TITLE
Enable a time selection method idependent of iloc/loc, called sel

### ISSUE THREAD

**Issue by khider** [LinkedEarth/paleoPandas#27]
Following the `.sel` method on `xarray dataarray`, we should enable a method allowing to select a specific point or slice. Example usage from xarray here: https://docs.xarray.dev/en/stable/user-guide/time-series.html#datetime-indexing

**Comment by khider** [comment]
The `.sel` method should allow users to select a portion of the timeseries based on 1. value or time  and 2. an argument, which can be a string, datetime (if time), float, list or a slice and set with an expression. 

Let's create a Series such as:
```
import numpy as np
import pyleoclim as pyleo

freqs=[1/20,1/80]
time=np.arange(2001)
signals=[]
for freq in freqs:
    signals.append(np.cos(2*np.pi*freq*time))
signal=sum(signals)

ts = pyleo.Series(time=time, value=signal)
```

Expected behavior from the following commands:

1. `ts1=ts.sel(value>1)`: returns a new timeseries object where all the values are greater than 1, with their corresponding time points. All operators should be allowed (`<`,`>`,`=`,`>=`,`<=`). 

2. `ts1=ts.sel(value=1, method = 'nearest', tolerance = 0.2)`: returns a new timeseries object where all the values are equal to 1, with their corresponding time points. In this particular example, some values should be equal to 1 but we can expect this behavior from real time series. Therefore, we need to build a tolerance, which is represented by the parameter `method` with an associated `tolerance` value. `Method` should allow for the following values `None`, means exact match only, and `nearest` (find the nearest values within the tolerance, which is the maximum distance between original and new labels for inexact matches). Default should be `None`. 

3. `ts1=ts.sel(value=[1, -1], method = 'nearest', tolerance = 0.2)`: returns a new timeseries object where all the values are equal to 1 or -1, with their corresponding time points. `method` and `tolerance` as previously defined. 

4. `ts1=ts.sel(value=slice(-1,1), method = 'nearest', tolerance = 0.2)`: returns a new timeseries object where all the values are between -1 and 1, with their corresponding time points. `method` and `tolerance` as previously defined.  The concept of a slice would most likely have to be defined in the code base. Perhaps as an object?


Now let's talk about time:

5. `ts1=ts.sel(time>1000)`: returns a new timeseries object where all the time values are greater than 1000 with their corresponding time points. The search criteria could be a float (`1000`) or a datetime object (`1995-12-31 10:17:25`) or a string (`"1995-12-31"`)

6. Following bullet 3. and 4., should be available for `=` and `slice`, the later being almost equivalent to the current `ts.slice()` which only takes floats as arguments.

**Comment by MarcoGorelli** [comment]
Thanks for the extra details. I'm to need a few more I'm afraid

First, `ts1=ts.sel(time>1000)` isn't valid Python syntax - how about `ts.sel(time=slice(1000, None))`?

Second, in what unit should the units be interpreted? How about
- if it's float, then in the same time unit of `ts`. For example, if the time unit of `ts` is `'years BP'`, then `1000` means `1000 years BP`
- if it's datetime, or a string, then interpret as the Gregorian Calendar. So `ts.sel(time=slice('1000-01-01', None))` means "all points where the datetime index is greater than the year `1000-01-01`. So, this is one is independent of `ts`'s time unit

> The concept of a slice would most likely have to be defined in the code base. Perhaps as an object?

`slice` is already a Python built-in, we can just use that

**Comment by MarcoGorelli** [comment]
Also, how should `tolerance` be interpreted if you pass a datetime to `time`?

**Comment by khider** [comment]
The first commit answers the first questions, and agreed and merged. 

Regarding the tolerance, maybe we should interpret is as a % for datetime? Or it should be given in datetime dt, which makes more sense.

**Comment by CommonClimate** [comment]
Addressed ( in part ) by https://github.com/LinkedEarth/Pyleoclim_util/pull/339
