### ISSUE TITLE
Leveraging pandas to align Series to each other

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/paleoPandas#28]
**Is your feature request related to a problem? Please describe.**
Currently, our only way to align Pyleoclim Series objects within a MultipleSeries collection is the `common_time()` method, which is a little clunky and does not make use of the new pandas non-ns indexing. 

**Describe the solution you'd like**
Explore using [align](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.align.html) or something similar to put the constituent Series objects of a MultipleSeries object on a common index. This should preserve the ability to internally combine observations using `interp()`, `bin()` or `gkernel()`, perhaps through dispatching. 

**Describe alternatives you've considered**
Keep doing it the old way, which is functional but clunky. 

@MarcoGorelli , @kcpevey , open to your suggestions, including "it's not worth our time!".

**Comment by CommonClimate** [comment]
I'll cook up a notebook to illustrate, @MarcoGorelli

**Comment by CommonClimate** [comment]
See [this notebook](https://github.com/LinkedEarth/paleoPandas/blob/main/notebooks/Series_Alignment.ipynb) for an explanation of the problem. Can you let me know what would be a good solution?

**Comment by MarcoGorelli** [comment]
> Explore using [align](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.align.html) or something similar to put the constituent Series objects of a MultipleSeries object on a common index

`align` assumes your indices are already compatible, it doesn't solve the problem of finding a common time step

**Comment by MarcoGorelli** [comment]
Closing as per discussion on Slack:

> I had a look into it, and I don't think it's possible (at least, not without a behaviour change) because the way you're binning is different to how pandas would do it (https://github.com/LinkedEarth/Pyleoclim_util/issues/340) .The method currently does a few things:
>
> 1. finds a common start time
> 2. finds a common end time
> 3. finds a common step
> 4. interpolates values in the new time scale
>
> If step 4 were rewritten to use pandas, it would come with a behaviour change. Given that a pure rewrite wouldn't be possible, and that there's still a few outstanding tasks, and that the scope of two closed ones has increased, I'm suggesting we drop this one.
