### ISSUE TITLE
Enable the selection of a calendar when working with datetime vs floats

### ISSUE THREAD

**Issue by khider** [LinkedEarth/paleoPandas#29]
Right now, Pyleoclim implements a conversion based on 365.25 days in a year. However, for model-data comparison, the data could be using the Gregorian calendar, Julian calendar, a 365days calendar or a combination. To support this work, the idea would be to incorporate CFtime into Pyleoclim.

**Comment by MarcoGorelli** [comment]
as discussed on Slack - shall we close this one, and assume that any conversion to Gregorian needs to happen before reaching pyleoclim?

**Comment by CommonClimate** [comment]
Yes, we are closing this as it is addressed by pr333
