### ISSUE TITLE
convert_datetime_index_to_time might not be correct

### ISSUE THREAD

**Issue by MarcoGorelli** [LinkedEarth/paleoPandas#31]
we're converting `2018-12-31` to `'-996.57775452'` with the time unit `'ma'`

this doesn't look right - the number of megaannums between 1950 and 2018 should be less than 1...

I'll take a look

This is the test I'm referring to:

https://github.com/LinkedEarth/Pyleoclim_util/blob/f1430bdb8b5117b3c136562c1ffcd79e53ae8272/pyleoclim/tests/test_utils_tsutils.py#L89-L99

**Comment by MarcoGorelli** [comment]
OK, got it, it's that `dataframe_dt.index` has nanosecond resolution, whereas the function's expecting second-resolution

fix incoming

**Comment by kcpevey** [comment]
@MarcoGorelli this can be closed now, right?

**Comment by MarcoGorelli** [comment]
yup!
